#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10.12

pipelines:
  custom:
    execute_employee_data:
      - step:
          name: Copy Employee Data for Email Signatures
          script:
            - pip install -r requirements.txt
            - python3 bamboo_azure.py
    execute_group_sync:
      - step:
          name: Create and Update Employee Groups
          script:
            - pip install -r requirements.txt
            - python3 sync_group_participation.py  # The second Python script to execute