#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10.12

pipelines:
  custom:
    execute:
      - step:
          name: execute script
          script:
            - pip install -r requirements.txt
            - python3 bamboo_azure.py