name: Create and Update Employee Groups

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'

permissions:
  contents: read

concurrency:
  group: execute-group-sync
  cancel-in-progress: false

jobs:
  execute-group-sync:
    name: Create and Update Employee Groups
    runs-on: ubuntu-latest
    environment: main
    container:
      image: python:3.10.12
    env:
      bamboo_hr_key: ${{ secrets.BAMBOO_HR_KEY }}
      azure_app_client_id: ${{ secrets.AZURE_APP_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      atlassian_user_id: ${{ secrets.ATLASSIAN_USER_ID }}
      atlassian_token: ${{ secrets.ATLASSIAN_TOKEN }}
      jumpcloud_token: ${{ secrets.JUMPCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync_group_participation.py
        run: python3 sync_group_participation.py
